project:
  type: website
  render:
    - README.qmd

website:
  title: "Health Equity Evidence Centre"
  navbar:
    left:
      - text: "Home"
        file: README.qmd
    right:
      - icon: github
        href: https://github.com/HealthEquityEvidenceCentre/HEEC

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Click to show code"