---
title: "Primary Care Network"
author: "Cameron Appel"
date: "2024-08-20"
format: gfm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)

library(dplyr)
library(magrittr)
```

# Primary Care Network

```{r 1}
# List all relevant files from the raw directory
files <- list.files("raw", pattern = "Primary Care Networks.*Individual Level.csv", full.names = TRUE)

# Load and combine all files
pcn <- lapply(files, function(file) {
  df <- read.csv(file)
  df <- df %>% 
    select(CENSUS_YEAR, CENSUS_MONTH,
           PCN_CODE, PCN_NAME, 
           ICB_CODE, ICB_NAME, STAFF_GROUP, 
           FTE)
  return(df)
}) %>% 
  bind_rows()

pcn %<>% group_by(CENSUS_YEAR, PCN_CODE, ICB_NAME, STAFF_GROUP) %>% summarise(FTE = sum(FTE, na.rm = TRUE)) %>% rename(Year = CENSUS_YEAR)

pcn %>% head()
```

# Get IMD from fingertipsR
```{r 2}
# Load necessary library
library(fingertipsR)

# Get the profile ID for the Public Health Outcomes Framework
profiles_data <- profiles()
phof_profile <- profiles_data[profiles_data$ProfileName == "Public Health Outcomes Framework", ]
profile_id <- phof_profile$ProfileID[1]

# Get indicators for the Public Health Outcomes Framework profile
indicators_data <- indicators(ProfileID = profile_id)

# Find the IndicatorID for "Deprivation score (IMD 2019)"
indicator_id <- indicators_data$IndicatorID[indicators_data$IndicatorName == "Deprivation score (IMD 2019)"]

# Get the data for the "Deprivation score (IMD 2019)" indicator
IMD <- fingertips_data(IndicatorID = indicator_id, AreaTypeID = 7) %>%
  select(c("ParentCode","Value")) %>% group_by(ParentCode) %>% summarise(IMD = mean(Value))

IMD %<>% rename(PCN_CODE = ParentCode)
# Display the first few rows of the data
head(IMD)
```

```{r 3}
pcn <- merge(pcn, IMD, by = "PCN_CODE") %>%
  group_by(Year) %>%
  mutate(IMD_quintile = ntile(IMD, 5))

# View the updated data frame
head(pcn)

write.csv(pcn, "pcn_workforce.csv", row.names = FALSE)
```